// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/audit/audit.proto

package auditpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuditRequest) Reset() {
	*x = UserAuditRequest{}
	mi := &file_proto_audit_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuditRequest) ProtoMessage() {}

func (x *UserAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audit_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuditRequest.ProtoReflect.Descriptor instead.
func (*UserAuditRequest) Descriptor() ([]byte, []int) {
	return file_proto_audit_audit_proto_rawDescGZIP(), []int{0}
}

func (x *UserAuditRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAuditRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *UserAuditRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListAllAuditsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllAuditsRequest) Reset() {
	*x = ListAllAuditsRequest{}
	mi := &file_proto_audit_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllAuditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllAuditsRequest) ProtoMessage() {}

func (x *ListAllAuditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audit_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllAuditsRequest.ProtoReflect.Descriptor instead.
func (*ListAllAuditsRequest) Descriptor() ([]byte, []int) {
	return file_proto_audit_audit_proto_rawDescGZIP(), []int{1}
}

func (x *ListAllAuditsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAllAuditsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type AuditLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Entity        string                 `protobuf:"bytes,4,opt,name=entity,proto3" json:"entity,omitempty"`
	EntityId      string                 `protobuf:"bytes,5,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,6,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_proto_audit_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audit_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_proto_audit_audit_proto_rawDescGZIP(), []int{2}
}

func (x *AuditLog) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *AuditLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLog) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *AuditLog) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AuditLog) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *AuditLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*AuditLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditResponse) Reset() {
	*x = AuditResponse{}
	mi := &file_proto_audit_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditResponse) ProtoMessage() {}

func (x *AuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audit_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditResponse.ProtoReflect.Descriptor instead.
func (*AuditResponse) Descriptor() ([]byte, []int) {
	return file_proto_audit_audit_proto_rawDescGZIP(), []int{3}
}

func (x *AuditResponse) GetLogs() []*AuditLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *AuditResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_audit_audit_proto protoreflect.FileDescriptor

const file_proto_audit_audit_proto_rawDesc = "" +
	"\n" +
	"\x17proto/audit/audit.proto\x12\x05audit\"Y\n" +
	"\x10UserAuditRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"D\n" +
	"\x14ListAllAuditsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xce\x01\n" +
	"\bAuditLog\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x16\n" +
	"\x06entity\x18\x04 \x01(\tR\x06entity\x12\x1b\n" +
	"\tentity_id\x18\x05 \x01(\tR\bentityId\x12#\n" +
	"\rmetadata_json\x18\x06 \x01(\tR\fmetadataJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"J\n" +
	"\rAuditResponse\x12#\n" +
	"\x04logs\x18\x01 \x03(\v2\x0f.audit.AuditLogR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\x92\x01\n" +
	"\fAuditService\x12>\n" +
	"\rGetUserAudits\x12\x17.audit.UserAuditRequest\x1a\x14.audit.AuditResponse\x12B\n" +
	"\rListAllAudits\x12\x1b.audit.ListAllAuditsRequest\x1a\x14.audit.AuditResponseB7Z5github.com/abubakvr/payup-backend/proto/audit;auditpbb\x06proto3"

var (
	file_proto_audit_audit_proto_rawDescOnce sync.Once
	file_proto_audit_audit_proto_rawDescData []byte
)

func file_proto_audit_audit_proto_rawDescGZIP() []byte {
	file_proto_audit_audit_proto_rawDescOnce.Do(func() {
		file_proto_audit_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_audit_audit_proto_rawDesc), len(file_proto_audit_audit_proto_rawDesc)))
	})
	return file_proto_audit_audit_proto_rawDescData
}

var file_proto_audit_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_audit_audit_proto_goTypes = []any{
	(*UserAuditRequest)(nil),     // 0: audit.UserAuditRequest
	(*ListAllAuditsRequest)(nil), // 1: audit.ListAllAuditsRequest
	(*AuditLog)(nil),             // 2: audit.AuditLog
	(*AuditResponse)(nil),        // 3: audit.AuditResponse
}
var file_proto_audit_audit_proto_depIdxs = []int32{
	2, // 0: audit.AuditResponse.logs:type_name -> audit.AuditLog
	0, // 1: audit.AuditService.GetUserAudits:input_type -> audit.UserAuditRequest
	1, // 2: audit.AuditService.ListAllAudits:input_type -> audit.ListAllAuditsRequest
	3, // 3: audit.AuditService.GetUserAudits:output_type -> audit.AuditResponse
	3, // 4: audit.AuditService.ListAllAudits:output_type -> audit.AuditResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_audit_audit_proto_init() }
func file_proto_audit_audit_proto_init() {
	if File_proto_audit_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_audit_audit_proto_rawDesc), len(file_proto_audit_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_audit_audit_proto_goTypes,
		DependencyIndexes: file_proto_audit_audit_proto_depIdxs,
		MessageInfos:      file_proto_audit_audit_proto_msgTypes,
	}.Build()
	File_proto_audit_audit_proto = out.File
	file_proto_audit_audit_proto_goTypes = nil
	file_proto_audit_audit_proto_depIdxs = nil
}
