// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/kyc/kyc.proto

package kycpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KYCService_GetKYCStatus_FullMethodName = "/kyc.KYCService/GetKYCStatus"
)

// KYCServiceClient is the client API for KYCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KYCServiceClient interface {
	GetKYCStatus(ctx context.Context, in *GetKYCStatusRequest, opts ...grpc.CallOption) (*GetKYCStatusResponse, error)
}

type kYCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKYCServiceClient(cc grpc.ClientConnInterface) KYCServiceClient {
	return &kYCServiceClient{cc}
}

func (c *kYCServiceClient) GetKYCStatus(ctx context.Context, in *GetKYCStatusRequest, opts ...grpc.CallOption) (*GetKYCStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKYCStatusResponse)
	err := c.cc.Invoke(ctx, KYCService_GetKYCStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KYCServiceServer is the server API for KYCService service.
// All implementations must embed UnimplementedKYCServiceServer
// for forward compatibility.
type KYCServiceServer interface {
	GetKYCStatus(context.Context, *GetKYCStatusRequest) (*GetKYCStatusResponse, error)
	mustEmbedUnimplementedKYCServiceServer()
}

// UnimplementedKYCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKYCServiceServer struct{}

func (UnimplementedKYCServiceServer) GetKYCStatus(context.Context, *GetKYCStatusRequest) (*GetKYCStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKYCStatus not implemented")
}
func (UnimplementedKYCServiceServer) mustEmbedUnimplementedKYCServiceServer() {}
func (UnimplementedKYCServiceServer) testEmbeddedByValue()                    {}

// UnsafeKYCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KYCServiceServer will
// result in compilation errors.
type UnsafeKYCServiceServer interface {
	mustEmbedUnimplementedKYCServiceServer()
}

func RegisterKYCServiceServer(s grpc.ServiceRegistrar, srv KYCServiceServer) {
	// If the following call panics, it indicates UnimplementedKYCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KYCService_ServiceDesc, srv)
}

func _KYCService_GetKYCStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKYCStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KYCServiceServer).GetKYCStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KYCService_GetKYCStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KYCServiceServer).GetKYCStatus(ctx, req.(*GetKYCStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KYCService_ServiceDesc is the grpc.ServiceDesc for KYCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KYCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kyc.KYCService",
	HandlerType: (*KYCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKYCStatus",
			Handler:    _KYCService_GetKYCStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/kyc/kyc.proto",
}
