// Package response provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package response

// ApiResponse defines model for ApiResponse.
type ApiResponse struct {
	Data         interface{} `json:"data"`
	Message      string      `json:"message"`
	ResponseCode string      `json:"responseCode"`
	Status       string      `json:"status"`
}
