// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/payment/payment.proto

package paymentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_Health_FullMethodName                         = "/payment.PaymentService/Health"
	PaymentService_CreateWallet_FullMethodName                   = "/payment.PaymentService/CreateWallet"
	PaymentService_ListWallets_FullMethodName                    = "/payment.PaymentService/ListWallets"
	PaymentService_DebitCreditWallet_FullMethodName              = "/payment.PaymentService/DebitCreditWallet"
	PaymentService_GetWaasTransactionHistory_FullMethodName      = "/payment.PaymentService/GetWaasTransactionHistory"
	PaymentService_GetWaasWalletStatus_FullMethodName            = "/payment.PaymentService/GetWaasWalletStatus"
	PaymentService_ChangeWalletStatus_FullMethodName             = "/payment.PaymentService/ChangeWalletStatus"
	PaymentService_SubmitWalletUpgrade_FullMethodName            = "/payment.PaymentService/SubmitWalletUpgrade"
	PaymentService_ListWalletUpgradeRequests_FullMethodName      = "/payment.PaymentService/ListWalletUpgradeRequests"
	PaymentService_GetWalletUpgradeRequest_FullMethodName        = "/payment.PaymentService/GetWalletUpgradeRequest"
	PaymentService_GetWalletUpgradeStatusByUserID_FullMethodName = "/payment.PaymentService/GetWalletUpgradeStatusByUserID"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PaymentService — add your payment RPCs here. Regenerate with protoc after editing.
type PaymentServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// CreateWallet creates a 9PSB wallet for the user. Payment service fetches KYC via gRPC, calls 9PSB, saves wallet and emits audit + notification via Kafka.
	CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletResponse, error)
	// ListWallets returns all wallets with details for admin view (decrypted account_number, full_name, etc.). Paginated.
	ListWallets(ctx context.Context, in *ListWalletsRequest, opts ...grpc.CallOption) (*ListWalletsResponse, error)
	// DebitCreditWallet performs an internal debit or credit on the user's wallet (airtime, data, electricity, DSTV, admin adjust). Saves to transactions and ledger.
	DebitCreditWallet(ctx context.Context, in *DebitCreditWalletRequest, opts ...grpc.CallOption) (*DebitCreditWalletResponse, error)
	// GetWaasTransactionHistory returns 9PSB WaaS transaction history for the given user's wallet (admin). Date range max 31 days.
	GetWaasTransactionHistory(ctx context.Context, in *GetWaasTransactionHistoryRequest, opts ...grpc.CallOption) (*GetWaasTransactionHistoryResponse, error)
	// GetWaasWalletStatus returns 9PSB WaaS wallet status for the given user's wallet (admin).
	GetWaasWalletStatus(ctx context.Context, in *GetWaasWalletStatusRequest, opts ...grpc.CallOption) (*GetWaasWalletStatusResponse, error)
	// ChangeWalletStatus changes the user's wallet status via 9PSB WaaS (ACTIVE or SUSPENDED). Updates DB, audit and email via Kafka.
	ChangeWalletStatus(ctx context.Context, in *ChangeWalletStatusRequest, opts ...grpc.CallOption) (*ChangeWalletStatusResponse, error)
	// SubmitWalletUpgrade submits a wallet tier upgrade to 9PSB (wallet_upgrade_file_upload). Fetches KYC + images via gRPC, sends multipart to 9PSB, audit + email via Kafka.
	SubmitWalletUpgrade(ctx context.Context, in *SubmitWalletUpgradeRequest, opts ...grpc.CallOption) (*SubmitWalletUpgradeResponse, error)
	// ListWalletUpgradeRequests returns wallet upgrade requests for admin (paginated). Newest first.
	ListWalletUpgradeRequests(ctx context.Context, in *ListWalletUpgradeRequestsRequest, opts ...grpc.CallOption) (*ListWalletUpgradeRequestsResponse, error)
	// GetWalletUpgradeRequest returns one wallet upgrade request by id (includes request/response payload JSON for admin detail).
	GetWalletUpgradeRequest(ctx context.Context, in *GetWalletUpgradeRequestRequest, opts ...grpc.CallOption) (*GetWalletUpgradeRequestResponse, error)
	// GetWalletUpgradeStatusByUserID returns wallet upgrade status for a user (latest request if any). Used by admin GET /users/:id/wallet/upgrade-status.
	GetWalletUpgradeStatusByUserID(ctx context.Context, in *GetWalletUpgradeStatusByUserIDRequest, opts ...grpc.CallOption) (*GetWalletUpgradeStatusByUserIDResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PaymentService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWalletResponse)
	err := c.cc.Invoke(ctx, PaymentService_CreateWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ListWallets(ctx context.Context, in *ListWalletsRequest, opts ...grpc.CallOption) (*ListWalletsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWalletsResponse)
	err := c.cc.Invoke(ctx, PaymentService_ListWallets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) DebitCreditWallet(ctx context.Context, in *DebitCreditWalletRequest, opts ...grpc.CallOption) (*DebitCreditWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DebitCreditWalletResponse)
	err := c.cc.Invoke(ctx, PaymentService_DebitCreditWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetWaasTransactionHistory(ctx context.Context, in *GetWaasTransactionHistoryRequest, opts ...grpc.CallOption) (*GetWaasTransactionHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWaasTransactionHistoryResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetWaasTransactionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetWaasWalletStatus(ctx context.Context, in *GetWaasWalletStatusRequest, opts ...grpc.CallOption) (*GetWaasWalletStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWaasWalletStatusResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetWaasWalletStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ChangeWalletStatus(ctx context.Context, in *ChangeWalletStatusRequest, opts ...grpc.CallOption) (*ChangeWalletStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeWalletStatusResponse)
	err := c.cc.Invoke(ctx, PaymentService_ChangeWalletStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) SubmitWalletUpgrade(ctx context.Context, in *SubmitWalletUpgradeRequest, opts ...grpc.CallOption) (*SubmitWalletUpgradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitWalletUpgradeResponse)
	err := c.cc.Invoke(ctx, PaymentService_SubmitWalletUpgrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ListWalletUpgradeRequests(ctx context.Context, in *ListWalletUpgradeRequestsRequest, opts ...grpc.CallOption) (*ListWalletUpgradeRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWalletUpgradeRequestsResponse)
	err := c.cc.Invoke(ctx, PaymentService_ListWalletUpgradeRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetWalletUpgradeRequest(ctx context.Context, in *GetWalletUpgradeRequestRequest, opts ...grpc.CallOption) (*GetWalletUpgradeRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletUpgradeRequestResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetWalletUpgradeRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetWalletUpgradeStatusByUserID(ctx context.Context, in *GetWalletUpgradeStatusByUserIDRequest, opts ...grpc.CallOption) (*GetWalletUpgradeStatusByUserIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletUpgradeStatusByUserIDResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetWalletUpgradeStatusByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
//
// PaymentService — add your payment RPCs here. Regenerate with protoc after editing.
type PaymentServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// CreateWallet creates a 9PSB wallet for the user. Payment service fetches KYC via gRPC, calls 9PSB, saves wallet and emits audit + notification via Kafka.
	CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletResponse, error)
	// ListWallets returns all wallets with details for admin view (decrypted account_number, full_name, etc.). Paginated.
	ListWallets(context.Context, *ListWalletsRequest) (*ListWalletsResponse, error)
	// DebitCreditWallet performs an internal debit or credit on the user's wallet (airtime, data, electricity, DSTV, admin adjust). Saves to transactions and ledger.
	DebitCreditWallet(context.Context, *DebitCreditWalletRequest) (*DebitCreditWalletResponse, error)
	// GetWaasTransactionHistory returns 9PSB WaaS transaction history for the given user's wallet (admin). Date range max 31 days.
	GetWaasTransactionHistory(context.Context, *GetWaasTransactionHistoryRequest) (*GetWaasTransactionHistoryResponse, error)
	// GetWaasWalletStatus returns 9PSB WaaS wallet status for the given user's wallet (admin).
	GetWaasWalletStatus(context.Context, *GetWaasWalletStatusRequest) (*GetWaasWalletStatusResponse, error)
	// ChangeWalletStatus changes the user's wallet status via 9PSB WaaS (ACTIVE or SUSPENDED). Updates DB, audit and email via Kafka.
	ChangeWalletStatus(context.Context, *ChangeWalletStatusRequest) (*ChangeWalletStatusResponse, error)
	// SubmitWalletUpgrade submits a wallet tier upgrade to 9PSB (wallet_upgrade_file_upload). Fetches KYC + images via gRPC, sends multipart to 9PSB, audit + email via Kafka.
	SubmitWalletUpgrade(context.Context, *SubmitWalletUpgradeRequest) (*SubmitWalletUpgradeResponse, error)
	// ListWalletUpgradeRequests returns wallet upgrade requests for admin (paginated). Newest first.
	ListWalletUpgradeRequests(context.Context, *ListWalletUpgradeRequestsRequest) (*ListWalletUpgradeRequestsResponse, error)
	// GetWalletUpgradeRequest returns one wallet upgrade request by id (includes request/response payload JSON for admin detail).
	GetWalletUpgradeRequest(context.Context, *GetWalletUpgradeRequestRequest) (*GetWalletUpgradeRequestResponse, error)
	// GetWalletUpgradeStatusByUserID returns wallet upgrade status for a user (latest request if any). Used by admin GET /users/:id/wallet/upgrade-status.
	GetWalletUpgradeStatusByUserID(context.Context, *GetWalletUpgradeStatusByUserIDRequest) (*GetWalletUpgradeStatusByUserIDResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPaymentServiceServer) CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWallet not implemented")
}
func (UnimplementedPaymentServiceServer) ListWallets(context.Context, *ListWalletsRequest) (*ListWalletsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWallets not implemented")
}
func (UnimplementedPaymentServiceServer) DebitCreditWallet(context.Context, *DebitCreditWalletRequest) (*DebitCreditWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DebitCreditWallet not implemented")
}
func (UnimplementedPaymentServiceServer) GetWaasTransactionHistory(context.Context, *GetWaasTransactionHistoryRequest) (*GetWaasTransactionHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWaasTransactionHistory not implemented")
}
func (UnimplementedPaymentServiceServer) GetWaasWalletStatus(context.Context, *GetWaasWalletStatusRequest) (*GetWaasWalletStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWaasWalletStatus not implemented")
}
func (UnimplementedPaymentServiceServer) ChangeWalletStatus(context.Context, *ChangeWalletStatusRequest) (*ChangeWalletStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeWalletStatus not implemented")
}
func (UnimplementedPaymentServiceServer) SubmitWalletUpgrade(context.Context, *SubmitWalletUpgradeRequest) (*SubmitWalletUpgradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitWalletUpgrade not implemented")
}
func (UnimplementedPaymentServiceServer) ListWalletUpgradeRequests(context.Context, *ListWalletUpgradeRequestsRequest) (*ListWalletUpgradeRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWalletUpgradeRequests not implemented")
}
func (UnimplementedPaymentServiceServer) GetWalletUpgradeRequest(context.Context, *GetWalletUpgradeRequestRequest) (*GetWalletUpgradeRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletUpgradeRequest not implemented")
}
func (UnimplementedPaymentServiceServer) GetWalletUpgradeStatusByUserID(context.Context, *GetWalletUpgradeStatusByUserIDRequest) (*GetWalletUpgradeStatusByUserIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletUpgradeStatusByUserID not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CreateWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateWallet(ctx, req.(*CreateWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ListWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWalletsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ListWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ListWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ListWallets(ctx, req.(*ListWalletsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_DebitCreditWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebitCreditWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).DebitCreditWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_DebitCreditWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).DebitCreditWallet(ctx, req.(*DebitCreditWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetWaasTransactionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWaasTransactionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetWaasTransactionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetWaasTransactionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetWaasTransactionHistory(ctx, req.(*GetWaasTransactionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetWaasWalletStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWaasWalletStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetWaasWalletStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetWaasWalletStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetWaasWalletStatus(ctx, req.(*GetWaasWalletStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ChangeWalletStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeWalletStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ChangeWalletStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ChangeWalletStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ChangeWalletStatus(ctx, req.(*ChangeWalletStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_SubmitWalletUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitWalletUpgradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).SubmitWalletUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_SubmitWalletUpgrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).SubmitWalletUpgrade(ctx, req.(*SubmitWalletUpgradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ListWalletUpgradeRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWalletUpgradeRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ListWalletUpgradeRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ListWalletUpgradeRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ListWalletUpgradeRequests(ctx, req.(*ListWalletUpgradeRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetWalletUpgradeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletUpgradeRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetWalletUpgradeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetWalletUpgradeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetWalletUpgradeRequest(ctx, req.(*GetWalletUpgradeRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetWalletUpgradeStatusByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletUpgradeStatusByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetWalletUpgradeStatusByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetWalletUpgradeStatusByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetWalletUpgradeStatusByUserID(ctx, req.(*GetWalletUpgradeStatusByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _PaymentService_Health_Handler,
		},
		{
			MethodName: "CreateWallet",
			Handler:    _PaymentService_CreateWallet_Handler,
		},
		{
			MethodName: "ListWallets",
			Handler:    _PaymentService_ListWallets_Handler,
		},
		{
			MethodName: "DebitCreditWallet",
			Handler:    _PaymentService_DebitCreditWallet_Handler,
		},
		{
			MethodName: "GetWaasTransactionHistory",
			Handler:    _PaymentService_GetWaasTransactionHistory_Handler,
		},
		{
			MethodName: "GetWaasWalletStatus",
			Handler:    _PaymentService_GetWaasWalletStatus_Handler,
		},
		{
			MethodName: "ChangeWalletStatus",
			Handler:    _PaymentService_ChangeWalletStatus_Handler,
		},
		{
			MethodName: "SubmitWalletUpgrade",
			Handler:    _PaymentService_SubmitWalletUpgrade_Handler,
		},
		{
			MethodName: "ListWalletUpgradeRequests",
			Handler:    _PaymentService_ListWalletUpgradeRequests_Handler,
		},
		{
			MethodName: "GetWalletUpgradeRequest",
			Handler:    _PaymentService_GetWalletUpgradeRequest_Handler,
		},
		{
			MethodName: "GetWalletUpgradeStatusByUserID",
			Handler:    _PaymentService_GetWalletUpgradeStatusByUserID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/payment/payment.proto",
}
