// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/user/user.proto

package userpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserServiceForKYC_GetUserForKYC_FullMethodName = "/user.UserServiceForKYC/GetUserForKYC"
)

// UserServiceForKYCClient is the client API for UserServiceForKYC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UserServiceForKYC is used by KYC service to validate and fetch user details when starting KYC.
type UserServiceForKYCClient interface {
	GetUserForKYC(ctx context.Context, in *GetUserForKYCRequest, opts ...grpc.CallOption) (*GetUserForKYCResponse, error)
}

type userServiceForKYCClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceForKYCClient(cc grpc.ClientConnInterface) UserServiceForKYCClient {
	return &userServiceForKYCClient{cc}
}

func (c *userServiceForKYCClient) GetUserForKYC(ctx context.Context, in *GetUserForKYCRequest, opts ...grpc.CallOption) (*GetUserForKYCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserForKYCResponse)
	err := c.cc.Invoke(ctx, UserServiceForKYC_GetUserForKYC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceForKYCServer is the server API for UserServiceForKYC service.
// All implementations must embed UnimplementedUserServiceForKYCServer
// for forward compatibility.
//
// UserServiceForKYC is used by KYC service to validate and fetch user details when starting KYC.
type UserServiceForKYCServer interface {
	GetUserForKYC(context.Context, *GetUserForKYCRequest) (*GetUserForKYCResponse, error)
	mustEmbedUnimplementedUserServiceForKYCServer()
}

// UnimplementedUserServiceForKYCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceForKYCServer struct{}

func (UnimplementedUserServiceForKYCServer) GetUserForKYC(context.Context, *GetUserForKYCRequest) (*GetUserForKYCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserForKYC not implemented")
}
func (UnimplementedUserServiceForKYCServer) mustEmbedUnimplementedUserServiceForKYCServer() {}
func (UnimplementedUserServiceForKYCServer) testEmbeddedByValue()                           {}

// UnsafeUserServiceForKYCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceForKYCServer will
// result in compilation errors.
type UnsafeUserServiceForKYCServer interface {
	mustEmbedUnimplementedUserServiceForKYCServer()
}

func RegisterUserServiceForKYCServer(s grpc.ServiceRegistrar, srv UserServiceForKYCServer) {
	// If the following call panics, it indicates UnimplementedUserServiceForKYCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserServiceForKYC_ServiceDesc, srv)
}

func _UserServiceForKYC_GetUserForKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserForKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceForKYCServer).GetUserForKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserServiceForKYC_GetUserForKYC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceForKYCServer).GetUserForKYC(ctx, req.(*GetUserForKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserServiceForKYC_ServiceDesc is the grpc.ServiceDesc for UserServiceForKYC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserServiceForKYC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserServiceForKYC",
	HandlerType: (*UserServiceForKYCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserForKYC",
			Handler:    _UserServiceForKYC_GetUserForKYC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/user.proto",
}

const (
	UserServiceForAdmin_ListUsers_FullMethodName         = "/user.UserServiceForAdmin/ListUsers"
	UserServiceForAdmin_GetUserForAdmin_FullMethodName   = "/user.UserServiceForAdmin/GetUserForAdmin"
	UserServiceForAdmin_SetUserRestricted_FullMethodName = "/user.UserServiceForAdmin/SetUserRestricted"
)

// UserServiceForAdminClient is the client API for UserServiceForAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UserServiceForAdmin is used by Admin service for portal: list users, get user, set restricted.
type UserServiceForAdminClient interface {
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	GetUserForAdmin(ctx context.Context, in *GetUserForAdminRequest, opts ...grpc.CallOption) (*GetUserForAdminResponse, error)
	SetUserRestricted(ctx context.Context, in *SetUserRestrictedRequest, opts ...grpc.CallOption) (*SetUserRestrictedResponse, error)
}

type userServiceForAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceForAdminClient(cc grpc.ClientConnInterface) UserServiceForAdminClient {
	return &userServiceForAdminClient{cc}
}

func (c *userServiceForAdminClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, UserServiceForAdmin_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceForAdminClient) GetUserForAdmin(ctx context.Context, in *GetUserForAdminRequest, opts ...grpc.CallOption) (*GetUserForAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserForAdminResponse)
	err := c.cc.Invoke(ctx, UserServiceForAdmin_GetUserForAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceForAdminClient) SetUserRestricted(ctx context.Context, in *SetUserRestrictedRequest, opts ...grpc.CallOption) (*SetUserRestrictedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserRestrictedResponse)
	err := c.cc.Invoke(ctx, UserServiceForAdmin_SetUserRestricted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceForAdminServer is the server API for UserServiceForAdmin service.
// All implementations must embed UnimplementedUserServiceForAdminServer
// for forward compatibility.
//
// UserServiceForAdmin is used by Admin service for portal: list users, get user, set restricted.
type UserServiceForAdminServer interface {
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	GetUserForAdmin(context.Context, *GetUserForAdminRequest) (*GetUserForAdminResponse, error)
	SetUserRestricted(context.Context, *SetUserRestrictedRequest) (*SetUserRestrictedResponse, error)
	mustEmbedUnimplementedUserServiceForAdminServer()
}

// UnimplementedUserServiceForAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceForAdminServer struct{}

func (UnimplementedUserServiceForAdminServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedUserServiceForAdminServer) GetUserForAdmin(context.Context, *GetUserForAdminRequest) (*GetUserForAdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserForAdmin not implemented")
}
func (UnimplementedUserServiceForAdminServer) SetUserRestricted(context.Context, *SetUserRestrictedRequest) (*SetUserRestrictedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserRestricted not implemented")
}
func (UnimplementedUserServiceForAdminServer) mustEmbedUnimplementedUserServiceForAdminServer() {}
func (UnimplementedUserServiceForAdminServer) testEmbeddedByValue()                             {}

// UnsafeUserServiceForAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceForAdminServer will
// result in compilation errors.
type UnsafeUserServiceForAdminServer interface {
	mustEmbedUnimplementedUserServiceForAdminServer()
}

func RegisterUserServiceForAdminServer(s grpc.ServiceRegistrar, srv UserServiceForAdminServer) {
	// If the following call panics, it indicates UnimplementedUserServiceForAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserServiceForAdmin_ServiceDesc, srv)
}

func _UserServiceForAdmin_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceForAdminServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserServiceForAdmin_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceForAdminServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServiceForAdmin_GetUserForAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserForAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceForAdminServer).GetUserForAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserServiceForAdmin_GetUserForAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceForAdminServer).GetUserForAdmin(ctx, req.(*GetUserForAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServiceForAdmin_SetUserRestricted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserRestrictedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceForAdminServer).SetUserRestricted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserServiceForAdmin_SetUserRestricted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceForAdminServer).SetUserRestricted(ctx, req.(*SetUserRestrictedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserServiceForAdmin_ServiceDesc is the grpc.ServiceDesc for UserServiceForAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserServiceForAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserServiceForAdmin",
	HandlerType: (*UserServiceForAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _UserServiceForAdmin_ListUsers_Handler,
		},
		{
			MethodName: "GetUserForAdmin",
			Handler:    _UserServiceForAdmin_GetUserForAdmin_Handler,
		},
		{
			MethodName: "SetUserRestricted",
			Handler:    _UserServiceForAdmin_SetUserRestricted_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/user.proto",
}
